global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.RateLimiting;
global using System.Threading.RateLimiting;
global using FluentValidation;
global using System.Text.Json;
global using AZ900Prep.Api.Domain.Entities;
global using AZ900Prep.Api.Infrastructure.Data;
global using AZ900Prep.Api.Common;
